Repository sous-chefs/postgresql, pull requests merged in 2022-12, with the labels that each got.

#704 Automated PR: Standardising Files
  .github/workflows/md-links.yml
  CHANGELOG.md
  chefignore
Labels: Release: Patch, Skip: Announcements

#706 Automated PR: Standardising Files
  CHANGELOG.md
  documentation/.gitkeep
Labels: Release: Patch, Skip: Announcements

#711 Connect as user `postgresql` to local file system socket
  CHANGELOG.md
  libraries/sql/_connection.rb
  test/cookbooks/test/recipes/access.rb
  test/cookbooks/test/recipes/extension.rb
  test/cookbooks/test/recipes/ident.rb
  test/cookbooks/test/recipes/initdb_locale.rb
Labels: Bug, Feature Request, Release: Minor

#713 Fix parsing of address field in `pga_hba.conf` (#712)
  CHANGELOG.md
  libraries/access.rb
  test/cookbooks/test/recipes/access.rb
  test/integration/access/controls/base_access.rb
Labels: Bug, Release: Patch
