Repository sous-chefs/postgresql, pull requests merged in 2023-07, with the labels that each got.

#751 Fix: allow multiple users/databases in postgresql_access resources
  CHANGELOG.md
  libraries/access.rb
  test/cookbooks/test/recipes/access.rb
Labels: Release: Minor

#753 Update lint-unit CI jobs to 2.0.5
  .github/workflows/ci.yml
Labels: Release: Patch

#754 Prevent triggering resource changes if file mode of postgresql.conf doesn't change
  CHANGELOG.md
  resources/config.rb
Labels: Bug, Release: Patch

#755 [GH-745] - fix PostgreSQL version detection
  CHANGELOG.md
  libraries/helpers.rb
Labels: Bug, Release: Patch
