Repository sous-chefs/postgresql, pull requests merged in 2023-05, with the labels that each got.

#740 Update CI permissions and remove MDL
  .github/workflows/ci.yml
  .github/workflows/md-links.yml
  CHANGELOG.md
Labels: Release: Patch, Skip: Announcements

#731 Fix unparsable pg_hba.conf when a column value is longer than the max width
  CHANGELOG.md
  libraries/access.rb
  test/cookbooks/test/recipes/access.rb
  test/integration/access/controls/base_access.rb
Labels: Release: Patch

#739 Make role encrypted_password idempotent
  CHANGELOG.md
  libraries/sql/role.rb
  resources/access.rb
  resources/config.rb
  resources/database.rb
  resources/extension.rb
  resources/ident.rb
  resources/role.rb
Labels: Bug, Release: Patch
