Repository sous-chefs/postgresql, pull requests merged in 2024-11, with the labels that each got.

#778 feat: Support PostgreSQL 17
  .github/copilot-instructions.md
  .github/workflows/ci.yml
  .markdownlint-cli2.yaml
  .rubocop.yml
  CHANGELOG.md
  documentation/postgresql_ident.md
  kitchen.yml
  libraries/_utils.rb
  libraries/access.rb
  libraries/helpers.rb
  libraries/ident.rb
  libraries/sql/_connection.rb
  metadata.rb
  resources/config.rb
  resources/install.rb
  templates/default/createcluster.conf.erb
  test/cookbooks/test/recipes/access.rb
  test/cookbooks/test/recipes/client_install.rb
  test/cookbooks/test/recipes/extension.rb
  test/cookbooks/test/recipes/ident.rb
  test/cookbooks/test/recipes/multi_client.rb
  test/cookbooks/test/recipes/server_install_os.rb
  test/integration/access/controls/base_access.rb
  test/integration/client_multi_install/controls/client_spec.rb
  test/integration/initdb_locale/controls/default_spec.rb
  test/integration/repo/controls/repo_spec.rb.rb
  test/integration/server_install/controls/server_spec.rb
  test/integration/server_install_os/controls/access.rb
Labels: Release: Major

#779 Automated PR: Cookstyle Changes
  CHANGELOG.md
  libraries/sql/_connection.rb
Labels: Release: Patch

#780 Automated PR: Standardising Files
  CHANGELOG.md
  kitchen.dokken.yml
Labels: Release: Patch, Skip: Announcements
