Repository sous-chefs/postgresql, pull requests merged in 2025-07, with the labels that each got.

#788 fix: rerun last release
  CHANGELOG.md
  documentation/postgresql_install.md
  metadata.rb
Labels: Release: Minor

#785 Automated PR: Standardising Files
  .vscode/extensions.json
  CHANGELOG.md
Labels: Skip: Announcements

#786 allow more mappings per mapname
  CHANGELOG.md
  documentation/postgresql_install.md
  libraries/ident.rb
  resources/ident.rb
  test/cookbooks/test/recipes/ident.rb
  test/integration/ident/controls/ident_map.rb
Labels: Feature Request, Release: Minor
